// A seed list of 150 widely-known touring DJs/producers, used only to make
// the artist search/autocomplete useful before you've logged anything
// yourself. Spans eras and genres so the search actually returns something
// for most queries.
export const SEED_ARTISTS = [
  // Contemporary house / techno / festival headliners
  "Fred again..",
  "Peggy Gou",
  "Honey Dijon",
  "Carl Cox",
  "Jamie xx",
  "Four Tet",
  "Bicep",
  "Charlotte de Witte",
  "Amelie Lens",
  "Black Coffee",
  "Solomun",
  "Nina Kraviz",
  "Ben Böhmer",
  "Bonobo",
  "Caribou",
  "Floating Points",
  "Jayda G",
  "Adam Beyer",
  "Richie Hawtin",
  "Sven Väth",
  "Loco Dice",
  "Seth Troxler",
  "Job Jobse",
  "DJ Koze",
  "Âme",
  "Dixon",
  "Move D",
  "Ricardo Villalobos",
  "Ross from Friends",
  "Overmono",
  "Danny Tenaglia",
  "Josh Wink",
  "Kerri Chandler",
  "Damian Lazarus",
  "Jamie Jones",
  "Hot Since 82",
  "Hannah Wants",
  "Patrick Topping",
  "Camelphat",
  "John Summit",
  "Fisher",
  "Chris Lake",
  "Green Velvet",
  "Claptone",
  "Purple Disco Machine",
  "Gorgon City",
  "Confidence Man",
  "Rüfüs Du Sol",
  "ANOTR",
  "Chris Stussy",
  "Vintage Culture",
  "Mochakk",
  "Vtss",
  "I Hate Models",
  "Sara Landry",
  "Boris Brejcha",
  "Tale Of Us",
  "Artbat",
  "Innellea",
  "Monolink",
  "Kx5",
  "Wax Motif",
  "Walker & Royce",
  // Trance / progressive
  "Paul van Dyk",
  "Armin van Buuren",
  "Ferry Corsten",
  "Paul Oakenfold",
  "Sasha",
  "John Digweed",
  "Danny Howells",
  "James Zabiela",
  "Above & Beyond",
  "Eric Prydz",
  // Big-room / EDM / pop crossover
  "David Guetta",
  "Calvin Harris",
  "Tiësto",
  "Marshmello",
  "Zedd",
  "Martin Garrix",
  "Deadmau5",
  "Diplo",
  "Skrillex",
  "DJ Snake",
  "Steve Aoki",
  "Kaskade",
  "Afrojack",
  "R3hab",
  "Don Diablo",
  "Oliver Heldens",
  "Nicky Romero",
  "W&W",
  "Jonas Blue",
  "Robin Schulz",
  "Jax Jones",
  "MK",
  // Bass / dubstep / trap
  "Excision",
  "Illenium",
  "Seven Lions",
  "Rezz",
  "Alison Wonderland",
  "What So Not",
  "RL Grime",
  "Baauer",
  "Zomboy",
  "Skream",
  "Benga",
  "Mala",
  "Kode9",
  // Drum & bass / jungle
  "Chase & Status",
  "Sub Focus",
  "Andy C",
  "Goldie",
  // Left-field / electronic acts
  "Kaytranada",
  "Disclosure",
  "Duke Dumont",
  "Flume",
  "ODESZA",
  "Porter Robinson",
  "Madeon",
  "The Chemical Brothers",
  "Underworld",
  "Orbital",
  "Leftfield",
  "Basement Jaxx",
  "Groove Armada",
  "Moby",
  "Fatboy Slim",
  "Justice",
  "Daft Punk",
  "Todd Terje",
  "Tiga",
  // House/techno pioneers & radio legends
  "Pete Tong",
  "Erick Morillo",
  "Roger Sanchez",
  "Bob Sinclar",
  "David Morales",
  "Frankie Knuckles",
  "Derrick Carter",
  "DJ Sneak",
  "Mark Farina",
  "Marshall Jefferson",
  "Jeff Mills",
  "Dave Clarke",
  "Laurent Garnier",
  "Chris Liebing",
  "Ben Klock",
  "Marcel Dettmann",
  "Helena Hauff",
  "DVS1",
  "Rebekah",
  "Perc",
  "Umek",
  "Joseph Capriati",
  "Marco Carola",
  "Paco Osuna",
  "Eats Everything",
  "Yousef",
  "DJ Harvey",
  "DJ Tennis",
  "Mall Grab",
  "DJ Seinfeld",
  "Joy Orbison",
  "Gilles Peterson",
  // Hip-hop / turntablism
  "DJ Jazzy Jeff",
  "Grandmaster Flash",
  "Afrika Bambaataa",
  "DJ Premier",
  "DJ Shadow",
  "A-Trak",
  "DJ Qbert",
  // Latin house / disco
  "Louie Vega",
  "Kenny Dope",
  // Afro house / amapiano
  "Culoe De Song",
  "Shimza",
  "Caiiro",
  "Uncle Waffles",
  "DJ Maphorisa",
  "Kabza De Small",
  "Sun-El Musician",
  "Black Motion",
];
