// A seed list of widely-known touring DJs/producers, used only to make the
// artist field autocomplete useful before you've logged anything yourself.
export const SEED_ARTISTS = [
  "Fred again..",
  "Peggy Gou",
  "Honey Dijon",
  "Carl Cox",
  "Jamie xx",
  "Four Tet",
  "Bicep",
  "Charlotte de Witte",
  "Amelie Lens",
  "Black Coffee",
  "Solomun",
  "Diplo",
  "Skrillex",
  "David Guetta",
  "Calvin Harris",
  "Tiësto",
  "Marshmello",
  "Kaytranada",
  "Disclosure",
  "Duke Dumont",
  "Nina Kraviz",
  "Ben Böhmer",
  "Bonobo",
  "Caribou",
  "Floating Points",
  "Jayda G",
  "DJ Snake",
  "Zedd",
  "Martin Garrix",
  "Deadmau5",
  "Above & Beyond",
  "Eric Prydz",
  "Adam Beyer",
  "Richie Hawtin",
  "Sven Väth",
  "Loco Dice",
  "Seth Troxler",
  "Job Jobse",
  "DJ Koze",
  "Âme",
  "Dixon",
  "Move D",
  "Ricardo Villalobos",
  "Ross from Friends",
  "Overmono",
  "Chase & Status",
  "Sub Focus",
  "Andy C",
  "Goldie",
  "Danny Tenaglia",
  "Josh Wink",
  "Kerri Chandler",
  "Damian Lazarus",
  "Jamie Jones",
  "Hot Since 82",
  "Hannah Wants",
  "Patrick Topping",
  "Camelphat",
  "John Summit",
  "Fisher",
  "Chris Lake",
  "Green Velvet",
  "Claptone",
  "Purple Disco Machine",
  "Gorgon City",
  "Disco Lines",
  "Confidence Man",
  "Rüfüs Du Sol",
  "ANOTR",
  "Chris Stussy",
  "Vintage Culture",
  "Mochakk",
  "Vtss",
  "I Hate Models",
  "Sara Landry",
  "Boris Brejcha",
  "Tale Of Us",
  "Artbat",
  "Innellea",
  "Monolink",
  "Kx5",
  "Wax Motif",
  "Walker & Royce",
];
