// A seed list of well-known nightclubs and festivals, used to make venue
// search/autocomplete useful before you've logged anything yourself.
// Deliberately global — DJ sets happen everywhere, not just near you —
// so this isn't location-biased the way a "search near me" places API
// would be. Anything not listed can still just be typed in freely.
export interface SeedVenue {
  name: string;
  city: string;
}

export const SEED_VENUES: SeedVenue[] = [
  // Nightclubs — North America
  { name: "Output", city: "Brooklyn, NY" },
  { name: "Elsewhere", city: "Brooklyn, NY" },
  { name: "Good Room", city: "Brooklyn, NY" },
  { name: "Nowadays", city: "Queens, NY" },
  { name: "Basement", city: "New York, NY" },
  { name: "Public Records", city: "Brooklyn, NY" },
  { name: "Brooklyn Mirage", city: "Brooklyn, NY" },
  { name: "Knockdown Center", city: "Queens, NY" },
  { name: "Smartbar", city: "Chicago, IL" },
  { name: "Spybar", city: "Chicago, IL" },
  { name: "The Mid", city: "Chicago, IL" },
  { name: "Sound Nightclub", city: "Los Angeles, CA" },
  { name: "Exchange LA", city: "Los Angeles, CA" },
  { name: "Academy LA", city: "Los Angeles, CA" },
  { name: "1015 Folsom", city: "San Francisco, CA" },
  { name: "Monarch", city: "San Francisco, CA" },
  { name: "Halcyon", city: "San Francisco, CA" },
  { name: "Space Miami", city: "Miami, FL" },
  { name: "E11EVEN Miami", city: "Miami, FL" },
  { name: "LIV Miami", city: "Miami Beach, FL" },
  { name: "Story Miami", city: "Miami Beach, FL" },
  { name: "Factory Town", city: "Miami, FL" },
  { name: "OMNIA", city: "Las Vegas, NV" },
  { name: "XS Nightclub", city: "Las Vegas, NV" },
  { name: "Marquee Nightclub", city: "Las Vegas, NV" },
  { name: "Hakkasan", city: "Las Vegas, NV" },
  { name: "Zouk Las Vegas", city: "Las Vegas, NV" },
  { name: "Tao Nightclub", city: "Las Vegas, NV" },

  // Nightclubs — Mexico / Latin America
  { name: "Vagalume", city: "Tulum, Mexico" },
  { name: "Papaya Playa Project", city: "Tulum, Mexico" },
  { name: "Warung Beach Club", city: "Santa Catarina, Brazil" },
  { name: "Green Valley", city: "Camboriú, Brazil" },
  { name: "D-Edge", city: "São Paulo, Brazil" },

  // Nightclubs — UK / Ireland
  { name: "fabric", city: "London, UK" },
  { name: "Printworks", city: "London, UK" },
  { name: "Ministry of Sound", city: "London, UK" },
  { name: "Egg London", city: "London, UK" },
  { name: "XOYO", city: "London, UK" },
  { name: "Studio 338", city: "London, UK" },
  { name: "E1", city: "London, UK" },
  { name: "The Cause", city: "London, UK" },
  { name: "Corsica Studios", city: "London, UK" },
  { name: "Village Underground", city: "London, UK" },
  { name: "Fold", city: "London, UK" },
  { name: "Warehouse Project", city: "Manchester, UK" },
  { name: "Sub Club", city: "Glasgow, UK" },

  // Nightclubs — Ibiza / Spain
  { name: "Pacha", city: "Ibiza, Spain" },
  { name: "Amnesia", city: "Ibiza, Spain" },
  { name: "DC10", city: "Ibiza, Spain" },
  { name: "Ushuaïa", city: "Ibiza, Spain" },
  { name: "Hï Ibiza", city: "Ibiza, Spain" },
  { name: "Blue Marlin Ibiza", city: "Ibiza, Spain" },
  { name: "Privilege", city: "Ibiza, Spain" },

  // Nightclubs — Continental Europe
  { name: "Berghain", city: "Berlin, Germany" },
  { name: "Tresor", city: "Berlin, Germany" },
  { name: "Watergate", city: "Berlin, Germany" },
  { name: "Kater Blau", city: "Berlin, Germany" },
  { name: "://about blank", city: "Berlin, Germany" },
  { name: "Sisyphos", city: "Berlin, Germany" },
  { name: "Robert Johnson", city: "Frankfurt, Germany" },
  { name: "Cocoon Club", city: "Frankfurt, Germany" },
  { name: "Rex Club", city: "Paris, France" },
  { name: "Concrete", city: "Paris, France" },
  { name: "De School", city: "Amsterdam, Netherlands" },
  { name: "Shelter", city: "Amsterdam, Netherlands" },
  { name: "RADION", city: "Amsterdam, Netherlands" },
  { name: "Trouw", city: "Amsterdam, Netherlands" },
  { name: "Paradiso", city: "Amsterdam, Netherlands" },
  { name: "Melkweg", city: "Amsterdam, Netherlands" },
  { name: "Toffler", city: "Rotterdam, Netherlands" },
  { name: "Fuse", city: "Brussels, Belgium" },
  { name: "La Rocca", city: "Antwerp, Belgium" },
  { name: "Club Bassiani", city: "Tbilisi, Georgia" },
  { name: "Khidi", city: "Tbilisi, Georgia" },

  // Nightclubs — Asia
  { name: "Womb", city: "Tokyo, Japan" },
  { name: "Contact Tokyo", city: "Tokyo, Japan" },
  { name: "ageHa", city: "Tokyo, Japan" },
  { name: "Circus Osaka", city: "Osaka, Japan" },
  { name: "Zouk Singapore", city: "Singapore" },
  { name: "Marquee Singapore", city: "Singapore" },

  // Festivals — North America
  { name: "Ultra Music Festival", city: "Miami, FL" },
  { name: "Electric Daisy Carnival (EDC Las Vegas)", city: "Las Vegas, NV" },
  { name: "Electric Forest", city: "Rothbury, MI" },
  { name: "Coachella", city: "Indio, CA" },
  { name: "Movement Detroit", city: "Detroit, MI" },
  { name: "Hard Summer", city: "Los Angeles, CA" },
  { name: "Beyond Wonderland", city: "San Bernardino, CA" },
  { name: "Lightning in a Bottle", city: "Buena Vista Lake, CA" },
  { name: "CRSSD Festival", city: "San Diego, CA" },
  { name: "Desert Hearts Festival", city: "Los Angeles, CA" },
  { name: "Shambhala Music Festival", city: "Salmo, BC" },
  { name: "Bass Coast Festival", city: "Merritt, BC" },
  { name: "Piknic Électronik", city: "Montreal, Canada" },
  { name: "MUTEK", city: "Montreal, Canada" },
  { name: "Burning Man", city: "Black Rock City, NV" },

  // Festivals — Mexico / Latin America
  { name: "Zamna Festival", city: "Tulum, Mexico" },
  { name: "Day Zero", city: "Tulum, Mexico" },
  { name: "APOKALIPSIS", city: "Tulum, Mexico" },

  // Festivals — UK / Ireland
  { name: "Creamfields", city: "Daresbury, UK" },
  { name: "Parklife", city: "Manchester, UK" },
  { name: "Boomtown Fair", city: "Winchester, UK" },
  { name: "We Are FSTVL", city: "Essex, UK" },
  { name: "Junction 2", city: "London, UK" },
  { name: "Glastonbury (Block9)", city: "Glastonbury, UK" },

  // Festivals — Continental Europe
  { name: "Tomorrowland", city: "Boom, Belgium" },
  { name: "Awakenings", city: "Amsterdam, Netherlands" },
  { name: "Time Warp", city: "Mannheim, Germany" },
  { name: "DGTL", city: "Amsterdam, Netherlands" },
  { name: "Dekmantel", city: "Amsterdam, Netherlands" },
  { name: "Sónar", city: "Barcelona, Spain" },
  { name: "Dour Festival", city: "Dour, Belgium" },
  { name: "Exit Festival", city: "Novi Sad, Serbia" },
  { name: "Balaton Sound", city: "Zamárdi, Hungary" },
  { name: "Kappa FuturFestival", city: "Turin, Italy" },
  { name: "Music On Festival", city: "Amsterdam, Netherlands" },
  { name: "Mysteryland", city: "Haarlemmermeer, Netherlands" },
  { name: "Loveland Festival", city: "Amsterdam, Netherlands" },
  { name: "Untold Festival", city: "Cluj-Napoca, Romania" },
  { name: "Airbeat One", city: "Neustadt-Glewe, Germany" },
  { name: "Nature One", city: "Kastellaun, Germany" },
  { name: "Fusion Festival", city: "Lärz, Germany" },
  { name: "Nuits Sonores", city: "Lyon, France" },
  { name: "Weather Festival", city: "Paris, France" },
  { name: "We Love Green", city: "Paris, France" },
  { name: "Sensation", city: "Amsterdam, Netherlands" },
  { name: "Defqon.1", city: "Biddinghuizen, Netherlands" },
  { name: "Decibel", city: "Netherlands" },

  // Festivals — Africa / Asia / Oceania
  { name: "Ultra South Africa", city: "Cape Town, South Africa" },
  { name: "Rocking the Daisies", city: "Cape Town, South Africa" },
  { name: "Wonderfruit", city: "Pattaya, Thailand" },
  { name: "ZoukOut", city: "Singapore" },
  { name: "Djakarta Warehouse Project", city: "Jakarta, Indonesia" },
  { name: "Road to Ultra Australia", city: "Melbourne, Australia" },
  { name: "Listen Out", city: "Sydney, Australia" },

  // More nightclubs / party spaces — North America
  { name: "Toejam Backlot", city: "Miami, FL" },
  { name: "Rebel Nightclub", city: "Toronto, Canada" },

  // More nightclubs — UK / Ireland
  { name: "Motion", city: "Bristol, UK" },

  // More nightclubs — Ibiza / Spain
  { name: "Eden Ibiza", city: "Ibiza, Spain" },
  { name: "Es Paradis", city: "Ibiza, Spain" },
  { name: "Octan Ibiza", city: "Ibiza, Spain" },
  { name: "Heart Ibiza", city: "Ibiza, Spain" },
  { name: "Café Mambo", city: "Ibiza, Spain" },
  { name: "Café del Mar", city: "Ibiza, Spain" },
  { name: "Booom!", city: "Ibiza, Spain" },
  { name: "Woomoon", city: "Ibiza, Spain" },
  { name: "Input", city: "Barcelona, Spain" },
  { name: "Razzmatazz", city: "Barcelona, Spain" },
  { name: "Moog", city: "Barcelona, Spain" },
  { name: "Fabrik", city: "Madrid, Spain" },
  { name: "Florida135", city: "Fraga, Spain" },

  // More nightclubs — Continental Europe
  { name: "Griessmuehle", city: "Berlin, Germany" },
  { name: "Renate", city: "Berlin, Germany" },
  { name: "Suicide Circus", city: "Berlin, Germany" },
  { name: "OST Club", city: "Warsaw, Poland" },
  { name: "Smolna", city: "Warsaw, Poland" },
  { name: "Fabrika", city: "Prague, Czech Republic" },
  { name: "Flex", city: "Vienna, Austria" },
  { name: "Grelle Forelle", city: "Vienna, Austria" },
  { name: "Yoyo", city: "Paris, France" },
  { name: "Machine du Moulin Rouge", city: "Paris, France" },
  { name: "Nouveau Casino", city: "Paris, France" },
  { name: "La Bellevilloise", city: "Paris, France" },
  { name: "Trädgår'n", city: "Gothenburg, Sweden" },
  { name: "Under Bron", city: "Stockholm, Sweden" },
  { name: "Culture Box", city: "Copenhagen, Denmark" },
  { name: "Jaeger", city: "Oslo, Norway" },
  { name: "Cocorico", city: "Riccione, Italy" },
  { name: "Amnesia Milano", city: "Milan, Italy" },
  { name: "Closer", city: "Kyiv, Ukraine" },
  { name: "K41", city: "Kyiv, Ukraine" },

  // More nightclubs — Asia / Oceania
  { name: "ALL", city: "Shanghai, China" },
  { name: "TAXX", city: "Bangkok, Thailand" },
  { name: "Beam", city: "Bangkok, Thailand" },
  { name: "Ce La Vi", city: "Singapore" },

  // More festivals — North America
  { name: "Sustain-Release", city: "Parksville, NY" },
  { name: "Freaky Deaky", city: "Dallas, TX" },
  { name: "Something Wicked", city: "Houston, TX" },
  { name: "Decadence", city: "Denver, CO" },
  { name: "Nocturnal Wonderland", city: "San Bernardino, CA" },
  { name: "Countdown NYE", city: "San Bernardino, CA" },
  { name: "Escape Halloween", city: "San Bernardino, CA" },
  { name: "Okeechobee Music Festival", city: "Okeechobee, FL" },
  { name: "III Points", city: "Miami, FL" },
  { name: "Sunset Music Festival", city: "Tampa, FL" },
  { name: "Framework Detroit", city: "Detroit, MI" },
  { name: "Holy Ship!", city: "at sea (cruise)" },
  { name: "Portola Music Festival", city: "San Francisco, CA" },
  { name: "Sonic Bloom", city: "Rye, CO" },
  { name: "Splash House", city: "Palm Springs, CA" },

  // More festivals — UK / Ireland
  { name: "Field Day", city: "London, UK" },
  { name: "Wide Awake Festival", city: "London, UK" },
  { name: "Gottwood Festival", city: "Anglesey, Wales" },
  { name: "Lost Village", city: "Lincolnshire, UK" },
  { name: "Houghton Festival", city: "Norfolk, UK" },
  { name: "Love Saves The Day", city: "Bristol, UK" },
  { name: "Beat-Herder Festival", city: "Ribble Valley, UK" },

  // More festivals — Continental Europe
  { name: "Amsterdam Open Air", city: "Amsterdam, Netherlands" },
  { name: "Primavera Sound", city: "Barcelona, Spain" },
  { name: "Sónar by Night", city: "Barcelona, Spain" },
  { name: "Off Week Barcelona", city: "Barcelona, Spain" },
  { name: "Sonus Festival", city: "Pag, Croatia" },
  { name: "Dimensions Festival", city: "Pula, Croatia" },
  { name: "Outlook Festival", city: "Pula, Croatia" },
  { name: "Circoloco at DC10", city: "Ibiza, Spain" },

  // More festivals — Africa / Asia / Oceania
  { name: "AfrikaBurn", city: "Tankwa Karoo, South Africa" },
  { name: "KreamFields", city: "Johannesburg, South Africa" },
  { name: "Good Vibes Festival", city: "Kuala Lumpur, Malaysia" },
  { name: "Ultra Korea", city: "Seoul, South Korea" },
  { name: "World DJ Festival", city: "Seoul, South Korea" },
  { name: "Golden Plains", city: "Meredith, Australia" },
  { name: "Meredith Music Festival", city: "Meredith, Australia" },
  { name: "Rainbow Serpent Festival", city: "Lexton, Australia" },
  { name: "Strawberry Fields Festival", city: "Tocumwal, Australia" },

  // Even more nightclubs — UK / Ireland
  { name: "KOKO", city: "London, UK" },
  { name: "Phonox", city: "London, UK" },
  { name: "Drumsheds", city: "London, UK" },
  { name: "Colour Factory", city: "London, UK" },
  { name: "Peckham Audio", city: "London, UK" },
  { name: "Bussey Building", city: "London, UK" },
  { name: "Oval Space", city: "London, UK" },
  { name: "Fire", city: "London, UK" },
  { name: "The Steel Yard", city: "London, UK" },
  { name: "O2 Academy Brixton", city: "London, UK" },
  { name: "Alexandra Palace", city: "London, UK" },
  { name: "Turnmills", city: "London, UK" },
  { name: "The End", city: "London, UK" },
  { name: "Lakota", city: "Bristol, UK" },
  { name: "Hidden", city: "Manchester, UK" },
  { name: "The White Hotel", city: "Manchester, UK" },
  { name: "Soup Kitchen", city: "Manchester, UK" },
  { name: "The Hacienda", city: "Manchester, UK" },
  { name: "Rainbow Venues", city: "Birmingham, UK" },
  { name: "Cream", city: "Liverpool, UK" },
  { name: "Gatecrasher", city: "Sheffield, UK" },

  // Even more nightclubs — North America
  { name: "House of Yes", city: "Brooklyn, NY" },
  { name: "Schimanski", city: "Brooklyn, NY" },
  { name: "Avant Gardner", city: "Brooklyn, NY" },
  { name: "Kings Hall", city: "Brooklyn, NY" },
  { name: "Le Bain", city: "New York, NY" },
  { name: "Webster Hall", city: "New York, NY" },
  { name: "Cielo", city: "New York, NY" },
  { name: "Verboten", city: "Brooklyn, NY" },
  { name: "Twilo", city: "New York, NY" },
  { name: "Limelight", city: "New York, NY" },
  { name: "Roxy NYC", city: "New York, NY" },
  { name: "Sound Factory", city: "New York, NY" },
  { name: "Paradise Garage", city: "New York, NY" },
  { name: "The Loft", city: "New York, NY" },
  { name: "Flash Factory", city: "Jersey City, NJ" },
  { name: "Stereo Live", city: "Houston, TX" },
  { name: "Concourse Project", city: "Austin, TX" },
  { name: "Elysium", city: "Houston, TX" },
  { name: "District Atlanta", city: "Atlanta, GA" },
  { name: "Believe Music Hall", city: "Atlanta, GA" },
  { name: "Opera Nightclub", city: "Atlanta, GA" },
  { name: "Cameo Nightclub", city: "Miami Beach, FL" },
  { name: "Treehouse Miami", city: "Miami, FL" },
  { name: "The Ground Miami", city: "Miami, FL" },
  { name: "Floyd", city: "Miami, FL" },
  { name: "Basement Miami", city: "Miami, FL" },
  { name: "Concord Music Hall", city: "Chicago, IL" },
  { name: "Radius Chicago", city: "Chicago, IL" },
  { name: "Prysm Nightclub", city: "Chicago, IL" },
  { name: "The Warehouse", city: "Chicago, IL" },
  { name: "Music Box", city: "Chicago, IL" },
  { name: "Public Works", city: "San Francisco, CA" },
  { name: "The End Up", city: "San Francisco, CA" },
  { name: "Audio", city: "San Francisco, CA" },
  { name: "Great Northern", city: "San Francisco, CA" },
  { name: "The Midway", city: "San Francisco, CA" },
  { name: "The Novo", city: "Los Angeles, CA" },
  { name: "Shrine Expo Hall", city: "Los Angeles, CA" },
  { name: "Avalon Hollywood", city: "Los Angeles, CA" },
  { name: "Bassmnt", city: "San Diego, CA" },
  { name: "Parq Nightclub", city: "San Diego, CA" },
  { name: "Beta Nightclub", city: "Denver, CO" },
  { name: "The Church Nightclub", city: "Denver, CO" },
  { name: "Kremwerk", city: "Seattle, WA" },
  { name: "Shady Park", city: "Tempe, AZ" },
  { name: "Century Grand", city: "Phoenix, AZ" },
  { name: "Holocene", city: "Portland, OR" },
  { name: "Union Transfer", city: "Philadelphia, PA" },
  { name: "Silk City", city: "Philadelphia, PA" },
  { name: "9:30 Club", city: "Washington, DC" },
  { name: "Flash", city: "Washington, DC" },
  { name: "Echostage", city: "Washington, DC" },
  { name: "Royale", city: "Boston, MA" },
  { name: "Big Night Live", city: "Boston, MA" },
  { name: "TV Lounge", city: "Detroit, MI" },
  { name: "Marble Bar", city: "Detroit, MI" },
  { name: "The Works", city: "Detroit, MI" },
  { name: "Spot Lite", city: "Detroit, MI" },
  { name: "Uniun", city: "Toronto, Canada" },
  { name: "Fifth Social Club", city: "Toronto, Canada" },
  { name: "The Guvernment", city: "Toronto, Canada" },
  { name: "Stereo Nightclub", city: "Montreal, Canada" },
  { name: "New City Gas", city: "Montreal, Canada" },
  { name: "Fortune Sound Club", city: "Vancouver, Canada" },
  { name: "The Red Room", city: "Vancouver, Canada" },

  // Even more nightclubs — Ibiza / Spain
  { name: "Lío", city: "Ibiza, Spain" },
  { name: "Destino Ibiza", city: "Ibiza, Spain" },
  { name: "Km5", city: "Ibiza, Spain" },
  { name: "Bora Bora Ibiza", city: "Ibiza, Spain" },

  // Even more nightclubs — Continental Europe
  { name: "Panorama Bar", city: "Berlin, Germany" },
  { name: "Chalet Berlin", city: "Berlin, Germany" },
  { name: "Anomalie Art Club", city: "Berlin, Germany" },
  { name: "Kraftwerk Berlin", city: "Berlin, Germany" },
  { name: "Prince Charles", city: "Berlin, Germany" },
  { name: "Club der Visionaere", city: "Berlin, Germany" },
  { name: "Else", city: "Berlin, Germany" },
  { name: "Bootshaus", city: "Cologne, Germany" },
  { name: "Institut für Zukunft", city: "Leipzig, Germany" },
  { name: "Distillery", city: "Leipzig, Germany" },
  { name: "Golden Pudel", city: "Hamburg, Germany" },
  { name: "Uebel & Gefährlich", city: "Hamburg, Germany" },
  { name: "Docks Hamburg", city: "Hamburg, Germany" },
  { name: "Garage Noord", city: "Amsterdam, Netherlands" },
  { name: "Doka", city: "Amsterdam, Netherlands" },
  { name: "Bitterzoet", city: "Amsterdam, Netherlands" },
  { name: "Now&Wow", city: "Rotterdam, Netherlands" },
  { name: "Djoon", city: "Paris, France" },
  { name: "Petit Bain", city: "Paris, France" },
  { name: "Papaya Club", city: "Novalja, Croatia" },
  { name: "Aquarius Club", city: "Novalja, Croatia" },
  { name: "Kalypso Club", city: "Novalja, Croatia" },
  { name: "Vega", city: "Copenhagen, Denmark" },
  { name: "Debaser", city: "Stockholm, Sweden" },
  { name: "Fabryka Trzciny", city: "Warsaw, Poland" },
  { name: "Selector", city: "Poznan, Poland" },

  // Nightclubs — Middle East
  { name: "WHITE Dubai", city: "Dubai, UAE" },
  { name: "Soho Garden", city: "Dubai, UAE" },
  { name: "BASE Dubai", city: "Dubai, UAE" },
  { name: "Zero Gravity", city: "Dubai, UAE" },
  { name: "Analog Room", city: "Dubai, UAE" },

  // Even more nightclubs — Asia
  { name: "Elevate", city: "Shanghai, China" },
  { name: "Arkham", city: "Shanghai, China" },
  { name: "Insomnia", city: "Bangkok, Thailand" },
  { name: "Sing Sing Theater", city: "Bangkok, Thailand" },
  { name: "Onyx", city: "Bangkok, Thailand" },
  { name: "Vurt", city: "Seoul, South Korea" },
  { name: "Cakeshop", city: "Seoul, South Korea" },
  { name: "Air (Studio Coast)", city: "Tokyo, Japan" },
  { name: "Vent", city: "Tokyo, Japan" },
  { name: "Sound Museum Vision", city: "Tokyo, Japan" },
  { name: "Kitty Su", city: "New Delhi, India" },
  { name: "antiSOCIAL", city: "Mumbai, India" },

  // Even more nightclubs — Oceania
  { name: "Home The Venue", city: "Sydney, Australia" },
  { name: "Chinese Laundry", city: "Sydney, Australia" },
  { name: "Ivy Nightclub", city: "Sydney, Australia" },
  { name: "Brown Alley", city: "Melbourne, Australia" },

  // Even more nightclubs — Africa
  { name: "Kong Rooftop", city: "Johannesburg, South Africa" },
  { name: "Truth Nightclub", city: "Johannesburg, South Africa" },
  { name: "Fiction Bar", city: "Cape Town, South Africa" },

  // Even more nightclubs — South America
  { name: "La Feria", city: "Buenos Aires, Argentina" },
  { name: "Crobar", city: "Buenos Aires, Argentina" },
  { name: "Mandarine Park", city: "Buenos Aires, Argentina" },
  { name: "The Week", city: "São Paulo, Brazil" },
  { name: "Cine Joia", city: "São Paulo, Brazil" },

  // Even more festivals — North America
  { name: "North Coast Music Festival", city: "Chicago, IL" },
  { name: "Spring Awakening", city: "Chicago, IL" },
  { name: "Electric Zoo", city: "New York, NY" },
  { name: "Moonrise Festival", city: "Baltimore, MD" },
  { name: "Breakaway Music Festival", city: "Columbus, OH" },
  { name: "Suwannee Hulaween", city: "Live Oak, FL" },
  { name: "Middlelands", city: "Todd Mission, TX" },
  { name: "Dirtybird Campout", city: "Lake Isabella, CA" },
  { name: "EDC Orlando", city: "Orlando, FL" },
  { name: "Envision Festival", city: "Uvita, Costa Rica" },

  // Even more festivals — Mexico / Latin America
  { name: "Corona Capital", city: "Mexico City, Mexico" },
  { name: "EDC Mexico", city: "Mexico City, Mexico" },
  { name: "The BPM Festival", city: "Playa del Carmen, Mexico" },
  { name: "Universo Paralelo", city: "Bahia, Brazil" },
  { name: "The Town", city: "São Paulo, Brazil" },
  { name: "Tomorrowland Brasil", city: "Itu, Brazil" },

  // Even more festivals — Continental Europe
  { name: "Ultra Europe", city: "Split, Croatia" },
  { name: "Fresh Island Festival", city: "Zrce Beach, Croatia" },
  { name: "Hideout Festival", city: "Zrce Beach, Croatia" },
  { name: "Sea Star Festival", city: "Umag, Croatia" },
  { name: "Electric Castle", city: "Cluj-Napoca, Romania" },
  { name: "Roskilde Festival", city: "Roskilde, Denmark" },
  { name: "Distortion Festival", city: "Copenhagen, Denmark" },
  { name: "Verknipt Festival", city: "Utrecht, Netherlands" },
  { name: "Nekst Festival", city: "Rotterdam, Netherlands" },
  { name: "Boom Festival", city: "Idanha-a-Nova, Portugal" },
  { name: "Waking Life", city: "Sao Mamede do Coronado, Portugal" },
  { name: "Storm Festival", city: "Crans-Montana, Switzerland" },
  { name: "Caprices Festival", city: "Crans-Montana, Switzerland" },
  { name: "Street Parade", city: "Zurich, Switzerland" },
  { name: "Melt Festival", city: "Ferropolis, Germany" },
  { name: "SonneMondSterne", city: "Saalburg-Ebersdorf, Germany" },
  { name: "Reworks Festival", city: "Thessaloniki, Greece" },
  { name: "Tomorrowland Winter", city: "Alpe d'Huez, France" },

  // Even more festivals — Asia
  { name: "Sunburn Festival", city: "Goa, India" },
  { name: "VH1 Supersonic", city: "Pune, India" },
  { name: "NH7 Weekender", city: "Pune, India" },

  // Even more festivals — Oceania
  { name: "Field Day", city: "Sydney, Australia" },
  { name: "Beyond The Valley", city: "Lardner Park, Australia" },
  { name: "Pitch Music & Arts", city: "Moyston, Australia" },
  { name: "Habitat Festival", city: "Mount Duneed, Australia" },
  { name: "Days Like This", city: "Melbourne, Australia" },
];
